image: node:18-alpine

stages:
  - test
  - sonarqube

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules
    - .sonar/cache

test:
  stage: test
  tags:
    - ohtu-build-4
  script:
    - npm install
    - npm test
  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
      - coverage/

sonarqube-check:
  stage: sonarqube
  tags:
    - ohtu-build-4
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  script:
    - sonar-scanner -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info